[package]
edition = "2021"
name = "bindings_wasm"
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys.workspace = true
serde-wasm-bindgen = "0.6.5"
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
xmtp_api_http = { path = "../xmtp_api_http" }
xmtp_cryptography = { path = "../xmtp_cryptography" }
xmtp_id = { path = "../xmtp_id" }
xmtp_mls = { path = "../xmtp_mls", features = ["message-history"] }

[dev-dependencies]
wasm-bindgen-test.workspace = true

[profile.release]
opt-level = "s"

[build]
target = "wasm32-unknown-unknown"

