[package]
description = "WASM bindings for the libXMTP rust library"
edition = "2021"
license = "MIT"
name = "bindings_wasm"
repository = "https://github.com/xmtp/libxmtp"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1.68"
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
js-sys = "0.3"
# log = { version = "0.4", features = ["std"] }
prost = { version = "^0.12", features = ["prost-derive"] }
prost-types = "^0.12"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
thiserror = "1.0"
futures = "0.3.30"
tokio = { version = "1.35.1", features = ["rt", "time"] }
tonic = "^0.11"
wasm-bindgen = "0.2.91"
wasm-bindgen-futures = "0.4.41"
xmtp_api_grpc = { path = "../xmtp_api_grpc" }
xmtp_cryptography = { path = "../xmtp_cryptography" }
xmtp_mls = { path = "../xmtp_mls", features = ["grpc", "native"] }
xmtp_proto = { path = "../xmtp_proto", features = ["proto_full"] }

[dev-dependencies]
ethers-core = "2.0.13"
uuid = { version = "1.3.1", features = ["v4"] }
wasm-bindgen-test = "0.3.41"

[profile.release]
opt-level = "s"
