[package]
name = "xps-client"
version = "0.1.0"
edition = "2021"
authors = ["XMTP Labs <eng@xmtp.com>"]
description = "XMTP XPS Client for decentralized operations"
homepage = "https://github.com/xmtp/libxmtp"
repository = "https://github.com/xmtp/libxmtp"
license = "MIT"
keywords = ["ethereum", "did", "did:ethr", "jsonrpc"]
categories = ["web-programming::websocket", "web-programming::http-server", "web-programming::http-client", "cryptography::cryptocurrencies"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee = { version = "0.22", features = ["client-core", "ws-client"] }
lib_xps = { git = "https://github.com/xmtp/xps-gateway", branch = "insipx/xps-timestamp", package = "lib-xps" }
xps-types = { git = "https://github.com/xmtp/xps-gateway", branch = "insipx/xps-timestamp", package = "xps-types" }
lib-didethresolver = { git =  "https://github.com/xmtp/didethresolver", branch = "insipx/xps-timestamp" }
xmtp_proto = { path = "../xmtp_proto", features = ["proto_full"] }
xmtp_mls = { path = "../xmtp_mls" }
xmtp_api_grpc = { path = "../xmtp_api_grpc" }
rustc-hex = "2.1"
url = "2.5"
hex.workspace = true
log.workspace = true
futures.workspace = true
async-trait.workspace = true
thiserror.workspace = true
openmls.workspace = true
tls_codec.workspace = true
ethers.workspace = true
prost.workspace = true
