[package]
name = "xmtpv3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
log = { version = "0.4", features = ["std"] }
thiserror = "1.0.56"
uniffi = { version = "0.25.3", features = [
  "tokio",
  "cli",
] }
uniffi_macros = "0.25.3"
xmtp_mls = { path = "../xmtp_mls", features = ["grpc", "native"] }
xmtp_cryptography = { path = "../xmtp_cryptography" }
xmtp_api_grpc = { path = "../xmtp_api_grpc" }
xmtp_v2 = { path = "../xmtp_v2" }
xmtp_proto = { path = "../xmtp_proto", features = ["proto_full", "grpc"]}
futures = "0.3.28"
tokio = { version = "1.28.1", features = ["macros"] }
xmtp_user_preferences = { path = "../xmtp_user_preferences" }

[build-dependencies]
uniffi = { version = "0.25.3", features = [
  "build",
] }

[[bin]]
name = "ffi-uniffi-bindgen"
path = "src/bin.rs"

[dev-dependencies]
ethers = "2.0.4"
ethers-core = "2.0.4"
tokio = { version = "1.28.1", features = ["full"] }
tempfile = "3.5.0"
uniffi = { version = "0.25.3", features = [
  "bindgen-tests",
] }

# NOTE: Thei release profile reduce bundle size from 230M to 41M - may have performance impliciations
# https://stackoverflow.com/a/54842093
[profile.release]
opt-level = 'z'   # Optimize for size
lto = true        # Enable link-time optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
panic = 'abort'   # Abort on panic
strip = true      # Strip symbols from binary*
