[package]
edition = "2021"
name = "xmtpv3"
version.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
futures.workspace = true
log = { version = "0.4", features = ["std"] }
parking_lot.workspace = true
thiserror.workspace = true
thread-id = "4.2.1"
tokio = { workspace = true, features = ["macros"] }
uniffi = { version = "0.28.0", features = ["tokio", "cli"] }
xmtp_api_grpc = { path = "../xmtp_api_grpc" }
xmtp_cryptography = { path = "../xmtp_cryptography" }
xmtp_id = { path = "../xmtp_id" }
xmtp_mls = { path = "../xmtp_mls", features = ["message-history"] }
xmtp_proto = { path = "../xmtp_proto", features = ["proto_full"] }
xmtp_user_preferences = { path = "../xmtp_user_preferences" }
xmtp_v2 = { path = "../xmtp_v2" }


[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }

[[bin]]
name = "ffi-uniffi-bindgen"
path = "src/bin.rs"

[dev-dependencies]
ethers = "2.0.13"
rand = "0.8.5"
tokio = { version = "1.28.1", features = ["full"] }
tokio-test = "0.4"
uniffi = { version = "0.28.0", features = ["bindgen-tests"] }
uuid = { version = "1.9", features = ["v4", "fast-rng"] }
xmtp_mls = { path = "../xmtp_mls", features = ["test-utils"] }
