[package]
name = "mls_validation_service"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "server"
path = "src/main.rs"

[dependencies]
prost = "0.12.1"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
tonic = "^0.9"
xmtp_proto = { path = "../xmtp_proto", features = ["xmtp-mls_validation-v1", "server"] }