[package]
name = "mls_validation_service"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "server"
path = "src/main.rs"

[dependencies]
prost = { version = "0.12.1", features = ["prost-derive"] }
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
tonic = "^0.9"
xmtp_proto = { path = "../xmtp_proto", features = ["xmtp-mls_validation-v1", "server"] }
openmls = { git= "https://github.com/openmls/openmls", features = ["test-utils"] }
openmls_traits = { git= "https://github.com/openmls/openmls" }
openmls_basic_credential = { git= "https://github.com/openmls/openmls" }
openmls_rust_crypto = { git= "https://github.com/openmls/openmls" }
xmtp_cryptography = { path = "../xmtp_cryptography" }
thiserror = "1.0.50"
ethers = "2.0.10"
serde = "1.0.189"
rand = "0.8.5"
hex = "0.4.3"
