name: Make release

on: 
  push:
    tags:
    - '*'

jobs:

  swift:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: build package
      working-directory: bindings_swift
      run: |
        make download-toolchains
        make swift
    - uses: actions/upload-artifact@v3
      with:
        name: xmtp-rust-swift
        path: bindings_swift/xmpt-rust-swift.zip

  release:
    runs-on: ubuntu-latest
    needs: swift
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: xmtp-rust-swift  
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
