name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  swift:
    runs-on: macos-12
    permissions:
      contents: write
    env:
      RELEASE_BRANCH: test-auto-release # do we want to push to main directly?
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: build package
      working-directory: bindings_swift
      run: |
        make download-toolchains
        make swift
    - uses: actions/checkout@v3
      with:
        repository: xmtp/xmtp-rust-swift
        path: xmtp-rust-swift
        ref: ${{ env.RELEASE_BRANCH }} 
    - name: push to xmtp-rust-swift
      working-directory: xmtp-rust-swift
      run: |
        unzip -o ../bindings_swift/xmtp-rust-swift.zip
        git config user.name libxmtp
        git config user.email libxmtp@xmtp.com
        git add .
        git commit -m "libxmtp release $GITHUB_REF"
        git tag $GITHUB_REF
        git push --tags origin $RELEASE_BRANCH
