services:
  node:
    image: xmtp/node-go@sha256:43d4da94f01cf2da60a8d46770d43c94d9c869bd3d01d94185aac49081851e60
    platform: linux/amd64
    environment:
      - GOWAKU-NODEKEY=8a30dcb604b0b53627a5adc054dbf434b446628d4bd1eccc681d223f0550ce67
    command:
      - --store.enable
      - --store.db-connection-string=postgres://postgres:xmtp@db:5432/postgres?sslmode=disable
      - --store.reader-db-connection-string=postgres://postgres:xmtp@db:5432/postgres?sslmode=disable
      - --mls-store.db-connection-string=postgres://postgres:xmtp@mlsdb:5432/postgres?sslmode=disable
      - --mls-validation.grpc-address=validation:50051
      - --api.enable-mls
      - --wait-for-db=30s
      # Disable authn until we have reliable support for generating auth tokens
      # - --api.authn.enable
    ports:
      - 5555:5555
      - 5556:5556
    depends_on:
      - db

  validation:
    image: ghcr.io/xmtp/mls-validation-service:main
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: ./dev/validation_service/local.Dockerfile

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp

  mlsdb:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp
